/**
 * Created by phoobobo on 2017/8/16.
 * Dragon Trail Interactive All Rights Reserved.
 */
export default {
    TAB_CONVERSATION : require('../../../img/tab_conversation.png'),
    TAB_MINE : require('../../../img/tab_my.png'),
    TAB_FORM: require('../../../img/tab_form.png'),
    NAV_BTN_LEFT_COMMON : require('../../../img/chatSource/chat_back_icon.png'),
    NAV_BTN_LEFT_WHITE  : require('../../../img/navBack_white.png'),
    // Chat Image Resource
    CHAT_NAV_LEFT   : require('../../../img/chatSource/chat_back_icon.png'),
    CHAT_NAV_RIGHT  : require('../../../img/chatSource/chat_right_icon.png'),
    CHAT_PHOTO_ICON : require('../../../img/chatSource/picture_icon.png'),
    CHAT_CAMERA_ICON: require('../../../img/chatSource/camera.png'),
    CHAT_SPEAK_ROUTINE: require('../../../img/chatSource/speakRoutine.png'),
    CHAT_ADD_ICON   : require('../../../img/chatSource/add.png'),
    CHAT_FOOT_VOICE : require('../../../img/chatSource/footer_voice_icon.png'),
    CHAT_FOOT_SCANF : require('../../../img/chatSource/footer_scanf_icon.png'),
    CHAT_FOOT_MORE  : require('../../../img/chatSource/footer_more_icon.png'),
    CHAT_FOOT_SENDER: require('../../../img/chatSource/sender_btn_icon.png'),
    CHAT_REC_MASK   : require('../../../img/chatSource/recording.gif'),
    CHAT_USR_DEFAULT: require('../../../img/chatSource/user_defaut.png'),
    CHAT_VOICE_ICON : require('../../../img/chatSource/voice_msg_icon.png'),
    CHAT_VOICE_SELF : require('../../../img/chatSource/voice_msg_icon_self.png'),
    CHAT_VOICE_GIF_ICON: require('../../../img/chatSource/voice_animated.gif'),
    CHAT_VOICE_GIF_SELF: require('../../../img/chatSource/voice_animated_self.gif'),
    CHAT_RIGHT_EXIT : require('../../../img/chatSource/exit_conversation.png'),
    CHAT_RIGHT_ANOTHER: require('../../../img/chatSource/another_user.png'),
    CHAT_RIGHT_HISTORY: require('../../../img/chatSource/history_conversation.png'),
    CHAT_RIGHT_USERINFO: require('../../../img/chatSource/user_info.png'),
    CUSTOMER_INFO_EDIT_REMARK: require('../../../img/chatSource/edit_remark.png'),
    CUSTOMER_INFO_SEX: require('../../../img/chatSource/sex.png'),
    CUSTOMER_INFO_ADDRESS: require('../../../img/chatSource/address.png'),
    CUSTOMER_INFO_DEVICE: require('../../../img/chatSource/device.png'),
    CUSTOMER_INFO_REMARK: require('../../../img/chatSource/remark.png'),
    CUSTOMER_INFO_SOURCE: require('../../../img/chatSource/source.png'),
    HISTORY_RIGHT_SEARCH: require('../../../img/chatSource/search_img.png'),
    HISTORY_RIGHT_CALENDAR: require('../../../img/chatSource/calendar.png'),
    HISTORY_SEARCH_NULL: require('../../../img/chatSource/empty_img.png'),
    CHAT_PRODUCT_MENU: require('../../../img/chatSource/product.png'),
    CHAT_PRODUCT_FILTER: require('../../../img/chatSource/filter_icon.png'),
    CHAT_PRODUCT_DATE: require('../../../img/chatSource/date_icon.png'),
    CHAT_PRODUCT_VOYAGE: require('../../../img/chatSource/voyage_icon.png'),
    CHAT_PRODUCT_ORDER: require('../../../img/chatSource/order.png'),
    CHAT_PRODUCT_DECREASE: require('../../../img/chatSource/decrease.png'),
    CHAT_PRODUCT_INCREASE: require('../../../img/chatSource/increase.png'),
    CHAT_WHPRODUCT_SEARCH: require('../../../img/chatSource/wh_search.png'),
    CHAT_WHPRODUCT_FILTER: require('../../../img/chatSource/wh_filter.png'),
    CHAT_WHPRODUCT_LOCATION: require('../../../img/chatSource/wh_location.png'),
    CHAT_WHPRODUCT_UPARROW: require('../../../img/chatSource/wh_arrowup.png'),
    CHAT_WHPRODUCT_DOWNARROW: require('../../../img/chatSource/wh_arrowdown.png'),
    CHAT_BLUEUPARROW: require('../../../img/chatSource/blueArrowUp.png'),
    CHAT_BLUEDOWNARROW: require('../../../img/chatSource/blueArrowDown.png'),
    // Login
    LOGO: require('../../../img/logo.png'),
    DEFAULT_LOGO: require('../../../img/default_img.png'),
    ACCOUNT: require('../../../img/loginSource/account.png'),
    PASSWORD: require('../../../img/loginSource/password.png'),
    CHECKCODE: require('../../../img/loginSource/checkcode.png'),
    UPSIDE_DOWN_TRIANGLE: require('../../../img/loginSource/upside_down_triangle.png'),
    CLEAR: require('../../../img/loginSource/close.png'),
    LESS_TRIANGLE: require('../../../img/loginSource/less.png'),
    // Conversation list Resource
    WAIT: require('../../../img/conversationListSource/wait.png'),
    ONLINE: require('../../../img/conversationListSource/online.png'),
    OFFLINE: require('../../../img/conversationListSource/offline.png'),
    MENU_ONLINE: require('../../../img/conversationListSource/menu_online.png'),
    MENU_OFFLINE: require('../../../img/conversationListSource/menu_offline.png'),
    NOTIFICATION_AVATAR: require('../../../img/conversationListSource/notification_avatar.png'),
    // Settings
    ICON_ENTRANCE: require('../../../img/icon_entrance.png'),
    CHANGE_PASSWORD: require('../../../img/mineSource/change_password.png'),
    NOTIFICATION: require('../../../img/mineSource/notification.png'),
    NOTIFICATION_IOS: require('../../../img/mineSource/notification_ios.png'),
    CLEANER: require('../../../img/mineSource/cleaner.png'),
    VERSION: require('../../../img/mineSource/version.png'),
    OLD_PASSWORD: require('../../../img/mineSource/old_password.png'),
    CONFIRM_PASSWORD: require('../../../img/mineSource/confirm_password.png'),
    ICON_MAIL: require('../../../img/mineSource/icon_mail.png'),
    // TabForm
    ICON_DATE: require('../../../img/tabForm/icon_date.png'),
    ICON_DOWN_TRIANGLE: require('../../../img/tabForm/icon_upsidedown_triangle.png'),
};
